### ISSUE TITLE
'source' field of 'display_data' is unclear

### ISSUE THREAD

**Issue by sn6uv** [jupyter/jupyter_client#120]
I'm writing a kernel and the docs:
```
Message type: display_data:
content = {
    # Who create the data
    'source' : str,
    ...
}```

are not at all clear what source should be.

Experimenting with the jupyter notebook, it seems as if it doesn't even matter what value is used?

**Comment by takluyver** [comment]
I think that's been removed from the messages, but it was forgotten in the documentation.

**Comment by sn6uv** [comment]
Is it okay to remove it from the docs then?

**Comment by willingc** [comment]
@takluyver @sn6uv Looking at the ``adapter.py`` code it looks like as Thomas mentions that the `source` field was removed in V5. Since it is still referred to in any adapter that converts from V4->V5 or the opposite, perhaps instead of completely removing (#121) it would be better to comment out the line ``'source': str,`` and add to the comment "Used in V4. Removed in V5."

https://github.com/jupyter/jupyter_client/blob/d82793dbdfb8589690dbdb96509c2814cadd444a/jupyter_client/adapter.py#L206

https://github.com/jupyter/jupyter_client/blob/d82793dbdfb8589690dbdb96509c2814cadd444a/jupyter_client/adapter.py#L277

https://github.com/jupyter/jupyter_client/blob/d82793dbdfb8589690dbdb96509c2814cadd444a/jupyter_client/adapter.py#L348

**Comment by takluyver** [comment]
I don't think we've done that for any of the other v4->v5 changes in the message spec, so I think it's fine to remove it.

**Comment by willingc** [comment]
Thanks for clarifying @takluyver. @sn6uv Thanks for the PR :+1:
