### ISSUE TITLE
Traitlets 4.3.1 gives me: DeprecationWarning: metadata {'config': True} was set from the constructor

### ISSUE THREAD

**Issue by tomdz** [jupyter/jupyter_client#248]
Traitlets 4.3.1 gives me this deprecation warning:
```
metadata {'config': True} was set from the constructor.
With traitlets 4.1, metadata should be set using the .tag() method,
e.g., Int().tag(key1='value1', key2='value2')
```
which I traced to this code block: https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/connect.py#L300

It goes away (or more precisely, complains about the next statement, line 300), when I change the code to:
```python
connection_file = Unicode('').tag(config=True,
help="""JSON file in which to store connection info [default: kernel-<pid>.json]

This file will contain the IP, ports, and authentication key needed to connect
clients to this kernel. By default, this file will be created in the security dir
of the current profile, but can be specified by absolute path.
""")
```

**Comment by rolweber** [comment]
jupyter_client currently doesn't require a minimum version of traitlets:
https://github.com/jupyter/jupyter_client/blob/ee9bd1ed3a4baa83166e18c9006799c1d13ea671/setup.py#L78
To get rid of deprecation warnings, we'll have to require a minimum version. Then we can change the code to use newer APIs instead of deprecated ones.

**Comment by minrk** [comment]
The `{'config': True} was set from the constructor`  deprecation was reverted in traitlets 4.3.2, so these shouldn't need updating anymore.
