### ISSUE TITLE
Traitlets 4.3.1 gives me: KernelSpecManager._data_dir_default is deprecated in traitlets 4.1

### ISSUE THREAD

**Issue by tomdz** [jupyter/jupyter_client#249]
Traitlets 4.3.1 gives me this warning:
```
DeprecationWarning: KernelSpecManager._data_dir_default is deprecated in traitlets 4.1
```
(the `_should_warn` key has `use @default decorator instead` in it).

**Comment by rolweber** [comment]
jupyter_client currently doesn't require a minimum version of traitlets:
https://github.com/jupyter/jupyter_client/blob/ee9bd1ed3a4baa83166e18c9006799c1d13ea671/setup.py#L78
To get rid of deprecation warnings, we'll have to require a minimum version. Then we can change the code to use newer APIs instead of deprecated ones.

**Comment by minrk** [comment]
The `_default` method deprecation was reverted in traitlets 4.3.2, so these do not need updates anymore. We can use `@default` as desired, but the deprecations on this are gone.
