### ISSUE TITLE
kernelspec kernel.json from deleted virtualenv will be used leading to kernel error

### ISSUE THREAD

**Issue by tonysimpson** [jupyter/jupyter_client#35]
Steps to reproduce
-----
 1. Install jupyter in a python virtualenv
 2. start jupyter notebook and create a new python notebook
 3. stop jupyter and delete the virtualenv
 4. create a new virtualenv with a different name to 1. and install jupyter
 5. start jupyter and create a python notebook or open the one from 2.
 6. "Kernel Error" appears in notebook

Notes
-----
I think this is probably WIP but I can't find any documentation on how it's supposed to work, closest I can find is https://ipython.org/ipython-doc/dev/development/kernels.html#kernelspecs but it's unclear if in the future we should manually configure and manage kernelspecs or some part of jupyter will do this for us. I would be happy to help fix this if the expected behaviour was specified.

Example kernel.json
-----

```json
{
 "language": "python",
 "display_name": "Python 3",
 "argv": [
  "C:\\Users\\tsimpson\\Envs\\jupyter\\Scripts\\python.exe",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ]
}
```

Workaround
-----
You can fix this by manually deleting the kernel config director containing the offending kernel.json and jupyter will then regenerate one using the current virtualenv.

System info
=========

```python
{'commit_hash': 'b754d5e',
 'commit_source': 'repository',
 'default_encoding': 'cp850',
 'ipython_path': 'c:\\users\\tsimpson\\envs\\jupyter\\src\\ipython\\IPython',
 'ipython_version': '4.0.0-dev',
 'os_name': 'nt',
 'platform': 'Windows-8-6.2.9200',
 'sys_executable': 'C:\\Users\\tsimpson\\Envs\\jupyter\\Scripts\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC '
                'v.1600 64 bit (AMD64)]'}
```

**Comment by takluyver** [comment]
This is a problem because in the Jupyter split, we switched from adding the native kernelspec to the list internally, to installing it if it doesn't exist. That assumes that the interpreter with which you first run the notebook is the standard Python interpreter you want. I don't think that's an assumption we should be making.

**Comment by minrk** [comment]
@takluyver do you mean we shouldn't register a Python kernelspec? That the IPython kernelspec should only be installed when explicitly requested by the user?

**Comment by minrk** [comment]
Or do you think we should more closely mimic the 3.0 behavior, and load the IPython kernel associated with the server's interpreter without installing it anywhere?

**Comment by takluyver** [comment]
The second one: we should ensure that the server's native kernel is available without actually installing it, because installing it assumes that the current interpreter will always be the one you want.

What I'm still not sure about is whether we should do this:

1. Always
2. When there's no kernel called `python{N}` installed 
3. When there are no kernels found at all

**Comment by minrk** [comment]
I wouldn't do 1. I've been annoyed in 3.x that it clobbers my python3 kernel unconditionally. I think I would do 2, since many upgrading users are likely to have installed one or more other kernels, but not IPython because it's not needed in 3.x, so they would not get IPython. I would probably even have a light warning in this case, and recommend that users install a default python2/3 kernel explicitly.

**Comment by takluyver** [comment]
I think 2 is sensible, though I'd prefer not to warn people - if we say that you should be doing `ipython kernelspec install-self`, people will end up in the same situation that prompted this bug report. And for users who just want to use it with a single Python interpreter, there's no real need to explicitly install a kernel spec.

I'll rustle up a couple of PRs to make that happen.

**Comment by minrk** [comment]
I think the question of the warning is really "do we want to encourage people to explicitly install the IPython kernelspec?" If the answer is no, then I agree that we shouldn't warn. If it's yes, I think some indication that they haven't done what we would like them to, but it will work anyway (e.g. warning-level message) is probably a good idea. I lean slightly toward the latter, but we should probably decide.
