### ISSUE TITLE
jupyter kernelspec error if python setuptools not installed

### ISSUE THREAD

**Issue by rjurga** [jupyter/jupyter_client#350]
Running `jupyter kernelspec` returns the following error if `python-setuptools` is not installed.

```
Traceback (most recent call last):
  File "/usr/bin/jupyter-kernelspec", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

`python-setuptools` is not listed as a required dependency. However `pytest` is an optional dependency, and `pytest` itself requires `python-setuptools`. So is there an assumption that running `jupyter kernelspec` is only for testing and requires `pytest`?

If not, that is to say if it is supposed to work in any circumstances, then should `python-setuptools` be added as a dependency to `jupyter_client`?

Thanks

**Comment by takluyver** [comment]
Try installing it with a newer version of pip - it shouldn't be creating scripts that import `pkg_resources`.

**Comment by rjurga** [comment]
Hi @takluyver, thanks for the answer. My use case is that I am installing the packaged version of the Linux distribution Solus, rather than installing through pip.

Linux distributions are packaging from the releases provided on this git repository, but since `python-setuptools` is not in the `install_requires` list of `setup.py`, it is not marked as a runtime dependency in the packages of Linux distributions. Hence the runtime error when doing `jupyter kernelspec`, since nothing else provides `pkg_resources` in Solus.

The question I hoped to answer by opening this issue is:
Should the Linux distributions that package `jupyter_client` use `python-setuptools` as a runtime dependency?

**Comment by takluyver** [comment]
From our point of view, setuptools is not a runtime dependency - our code doesn't load it, and when you install Jupyter directly from PyPI, the scripts created shouldn't need it.

For downstream distributors like Solus, I suspect there are a couple of options:

- Make pip a build dependency, and install into the build environment with `pip install --no-deps .` rather than `python setup.py install`. This should create scripts that don't rely on setuptools.
- Add setuptools as a runtime dependency.
- Run `python setup.py install` but then rewrite the scripts so they don't need pkg_resources. E.g. `jupyter-kernelspec` can be:

```python
from jupyter_client.kernelspecapp import KernelSpecApp
KernelSpecApp.launch_instance()
```

This problem should affect most Python packages which install shell commands, so the packagers for your distro should have a standard answer for what to do.

**Comment by rjurga** [comment]
I'm forwarding this to the Solus developers since it is a downstream issue. Thanks for the suggested solutions.
