### ISSUE TITLE
Restarter callbacks not being called

### ISSUE THREAD

**Issue by mlucool** [jupyter/jupyter_client#417]
Hi,

Pardon my lack of understanding if this is not a bug in this repo, but a downstream jupyter package.

Using version `5.2.3`, I see that in `KernelManager` the restarter callbacks are not called on restarts. From [here](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L313), it seems the first thing that a restart does is stop the restarter monitor and I don't see it started/called later. This may be a downstream bug with something else, but it looks like it stems from here. Ultimately, I don't see `on_kernel_restart` being called in [ZMQChannelsHandler](https://github.com/jupyter/notebook/blob/64fa7cf6748c6ba2965aadd337b7edb7bb26b306/notebook/services/kernels/handlers.py#L476) which is where I want to add in logic.

**Comment by xmnlab** [comment]
hi @mlucool could you provide more information?

not sure if makes sense call `start_restarter` inside `shutdown_kernel` function.

**Comment by kevin-bates** [comment]
I think there may be a misunderstanding on when the restart callbacks come into play (i.e., get fired).  They are fired when the polling mechanism detects the kernel is no longer alive via the built-in _auto-restart_ mechanism.  When a previously started kernel is detected to no longer be alive (outside an explicit shutdown action), juptyer_client will attempt to restart the kernel and this is when any [registered callbacks should get fired](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/restarter.py#L93-L114).  This scenario is different than the intentional 'Restart kernel' action from the client Notebook/Lab instance, in which case a more explicit shutdown/startup sequence occurs.

Might this explain why you don't see the callbacks fired?  Or are you attempting to 'hook' the auto-detected kernel failures prior to (automatic) restarts and still not seeing your callbacks?

I don't know the history behind the implementation to know if restart callbacks are expected to fire when the restart is intentional, but that doesn't appear to be the case.

**Comment by mlucool** [comment]
Thanks @kevin-bates and @xmnlab 

I am not attempting to hook in before. I actually just need a way to know when a kernel was restarted in `ZMQChannelsHandler`. I am subclassing it and need to know on every kernel startup so that I need to run code (we are injecting something into the kernel). Is there another method I should be looking at in this handler? I would have expected [on_kernel_restarted](https://github.com/jupyter/notebook/blob/64fa7cf6748c6ba2965aadd337b7edb7bb26b306/notebook/services/kernels/handlers.py#L476) to be the right place based on its name.

**Comment by kevin-bates** [comment]
Yeah, I agree there's ambiguity here.  `on_kernel_restarted` should probably be `on_kernel_died` - especially since it fires before the restart method gets called.

I'm not very familiar with this area of the server, but I'm wondering if `open()` is the method you want.  It is called on startup and restarts and that would fit your statement _"and need to know on every kernel startup"_.  However, I believe it's also called on any reconnects.  As a result, you'd probably need a combination of KernelManager and handler changes since you could then override `restart_kernel()` or `start_kernel()` (if you need all starts).

**Comment by mlucool** [comment]
My code is idempotent, so it's not terrible if its run more than once. That being said, I do not see `open(self, kernel_id)` being called on restarts. I added a print to see if it was being called but I see only the initial open:

```
WARNING 14:04:46 Opening d038f600-4c32-4620-a08f-d44fea424fcf
INFO 14:04:52 Kernel restarted: d038f600-4c32-4620-a08f-d44fea424fcf
```

I am restarting the kernel via the `@jupyterlab/services` api's: `kernel.restart()` which appears to be calling something like `api/kernels/a402aa4a-4cb4-4d17-8ce5-4c16ddf0e222/restart?1554228579384`. 
This also seems to be still using the same websocket before and after restart based on messages sent in `api/kernels/a402aa4a-4cb4-4d17-8ce5-4c16ddf0e222/channels?session_id=9b5a52749795b1edde964a3d2d840e3a`. This would imply that between restarts the channel id is the same, so open would not need to be called.

**Comment by mlucool** [comment]
With your comment I was able to get something working via a monkey patch. Please let me know if you have any better ideas. Below does have the problem of chaining callbacks, whose fix would be the same as just adding this notify ability to the kernel_manager itself.

```
    def open(self, kernel_id):
        super(MyZMQChannelsHandler, self).open(kernel_id)

        import types
        original_restart_kernel = self.kernel_manager.restart_kernel
        def restart_kernel_and_inject(km_self, kernel_id):
            if self.kernel_id == kernel_id:
                self._injected_code = False
            return original_restart_kernel(kernel_id)

        self.kernel_manager.restart_kernel = types.MethodType(restart_kernel_and_inject, self.kernel_manager)
        self._original_restart_kernel = original_restart_kernel

    def close(self):
        self.kernel_manager.restart_kernel = self._original_restart_kernel
        return super(MyZMQChannelsHandler, self).close()
```

**Comment by kevin-bates** [comment]
Hmm - strange.  So you don't see a message like this on each restart if you have `DEBUG` enabled?
```
[D 13:09:50.844 NotebookApp] Opening websocket /api/kernels/4d8b2e47-3d08-4bd3-bf5c-aab93fba2abb/channels
```
I also see "restoring connection" info messages on each restart.
```
[I 13:09:50.848 NotebookApp] Restoring connection for 4d8b2e47-3d08-4bd3-bf5c-aab93fba2abb:4cbf4424bf8d4d92a8ba907ec0da0dc9
```
So there are some differences in behavior here (I'm essentially running the master notebook branch). 

At any rate, I prefer the subclass approach rather than 'patching' (but that's probably more due to my unfamiliarity with Python itself) and just wanted to get you moving forward from the auto-restart callbacks.

Sounds like this issue could be closed at this point.  Good luck.

**Comment by mlucool** [comment]
No I do not see a restoring connection message. It somewhat surprisingly looks like this:

```
DEBUG 19:43:15 200 OPTIONS /myapi/api/kernels/8254c801-0759-4c95-a69e-6c1a1cba2919/restart?1554248595633 (10.218.24.247) 1.52ms
DEBUG 19:43:16 Starting kernel: ['/usr/local/bin/python2', '-m', 'ipykernel_launcher', '-f', '/run/user/13403/jupyter/kernel-8254c801-0759-4c95-a69e-6c1a1cba2919.json']
DEBUG 19:43:16 Connecting to: tcp://127.0.0.1:58817
INFO 19:43:16 Kernel restarted: 8254c801-0759-4c95-a69e-6c1a1cba2919
DEBUG 19:43:16 Connecting to: tcp://127.0.0.1:34461
DEBUG 19:43:16 activity on 8254c801-0759-4c95-a69e-6c1a1cba2919: status
DEBUG 19:43:16 activity on 8254c801-0759-4c95-a69e-6c1a1cba2919: shutdown_reply
DEBUG 19:43:16 activity on 8254c801-0759-4c95-a69e-6c1a1cba2919: status
DEBUG 19:43:16 activity on 8254c801-0759-4c95-a69e-6c1a1cba2919: status
DEBUG 19:43:16 activity on 8254c801-0759-4c95-a69e-6c1a1cba2919: status
DEBUG 19:43:16 activity on 8254c801-0759-4c95-a69e-6c1a1cba2919: status
DEBUG 19:43:16 Kernel info reply received: 8254c801-0759-4c95-a69e-6c1a1cba2919
DEBUG 19:43:16 200 POST /myapi/api/kernels/8254c801-0759-4c95-a69e-6c1a1cba2919/restart?1554248595633 (10.218.24.247) 728.89ms
```

Anyway, thanks for your help. Closing.
