### ISSUE TITLE
Repeating protocol adapter messages signal crash (too many file descriptors)

### ISSUE THREAD

**Issue by ralphmrm1** [jupyter/jupyter_client#463]
Jupyter lab 1.0.2 (local) on Windows 10 (1903).

The problem exists with (for example) Julia 1.1.0 and Javascript (Node.js) kernels, not (for example) with Python 3 or Scilab.

When a Julia tab is opened, `Adapting from protocol 5.0 to 5.3` messages are repeated every 10 seconds in the PowerShell window until (after ~15 minutes) the kernel crashes with the following output:
```
[I 18:00:09.662 LabApp] Shutting down 1 kernel
[I 18:00:14.757 LabApp] Kernel shutdown: b4a4bdfb-339e-40a5-a195-bcecdfb3c7dd
Traceback (most recent call last):
File “d:\python37\lib\runpy.py”, line 193, in _run_module_as_main*
“main”, mod_spec)*
File “d:\python37\lib\runpy.py”, line 85, in _run_code*
exec(code, run_globals)*
File “d:\python37\scripts\jupyter-lab.EXE_main_.py”, line 9, in *
File “d:\python37\lib\site-packages\jupyter_core\application.py”, line 267, in launch_instance*
return super(JupyterApp, cls).launch_instance(argv=argv, *kwargs)
File “d:\python37\lib\site-packages\traitlets\config\application.py”, line 658, in launch_instance*
app.start()*
File “d:\python37\lib\site-packages\notebook\notebookapp.py”, line 1857, in start*
self.io_loop.start()*
File “d:\python37\lib\site-packages\tornado\platform\asyncio.py”, line 132, in start*
self.asyncio_loop.run_forever()*
File “d:\python37\lib\asyncio\base_events.py”, line 534, in run_forever*
self._run_once()*
File “d:\python37\lib\asyncio\base_events.py”, line 1735, in _run_once*
event_list = self._selector.select(timeout)*
File “d:\python37\lib\selectors.py”, line 323, in select*
r, w, _ = self._select(self._readers, self._writers, , timeout)*
File “d:\python37\lib\selectors.py”, line 314, in _select*
r, w, x = select.select(r, w, w, timeout)*
ValueError: too many file descriptors in select()
```
Essentially the same thing happens using the Javascript (node.js) kernel except that the messages indicate `Adapting from protocol 5.1 to 5.3`  rather than from 5.0.

If I open a Python 3 tab *after* opening the Julia tab, the repeated `Adapting` messages cease, and the Julia kernel does not crash. Opening another Julia tab restarts them... etc.

**Comment by stevengj** [comment]
(From the [Julia discussion board](https://discourse.julialang.org/t/jupyterlab-ijulia-kernel-too-many-file-descriptors-in-select).)

**Comment by kleinhenz** [comment]
I am also seeing this behavior on linux after updating jupyter

**Comment by ralphmrm1** [comment]
Another jupyterlab version (1.0.3) has appeared and the problem seems to be fixed. Updated using

python -m pip install -U jupyterlab

and also performed the rebuild when jupyterlab suggested on restart.

**Comment by jasongrout** [comment]
This may have been fixed because we included a leniency for the non-compliant Julia kernel_info_reply messages in JLab 1.0.3:  https://github.com/jupyterlab/jupyterlab/pull/6860 (see also https://github.com/jupyterlab/jupyterlab/issues/6826 for further discussion)

**Comment by jasongrout** [comment]
Essentially, the Julia kernel apparently does not set the status field on kernel_info_reply messages, and jlab 1 started checking that status field. However, since this was a tricky area of the spec to get right, and the classic notebook ignored this field on kernel_info_reply messages, we decided to treat this field as optional on kernel_info_reply messages, at least until there is a better compliance testing framework for kernels so kernels can easily see where their messages are not compliant with the spec.

**Comment by kevin-bates** [comment]
I've run into this same issue with the Apache Toree (Scala) kernel recently while performing a POC of the [jupyter_kernel_mgmt](https://github.com/takluyver/jupyter_kernel_mgmt) (aka Kernel Providers) proposal in which that code also expects a status field present on kernel_info_reply.

The same was true for the IRkernel, but I noticed I was using an older version and this issue was addressed in a release only a couple weeks ago.  I totally agree that this should be relaxed until kernel developers have a chance to a) catch wind of this and b) apply the update.

>  jlab 1 started checking that status field

@jasongrout - what does jlab1 use for its message handling?  I figured it relied on the same libraries as notebook.  If different, and not the same as the [POC I'm looking at](https://github.com/takluyver/jupyter_kernel_mgmt/blob/master/jupyter_kernel_mgmt/client.py#L81), then that implies three different code bases for this.  Could you please share the code location used in jlab 1?

**Comment by jasongrout** [comment]
> what does jlab1 use for its message handling

Remember jlab is a typescript (javascript) web-based application. It uses its own typescript implementation, not a python implementation. And nteract also has its own javascript message processing library too.

JupyterLab's implementation is at https://github.com/jupyterlab/jupyterlab/tree/master/packages/services/src/kernel, in particular https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/messages.ts and https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/validate.ts https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/default.ts. The change in question is  jupyterlab/jupyterlab#6860

**Comment by jasongrout** [comment]
> The same was true for the IRkernel, but I noticed I was using an older version and this issue was addressed in a release only a couple weeks ago.

IIRC, this came from conversations stemming from this issue: https://github.com/jupyterlab/jupyterlab/issues/6760

**Comment by jasongrout** [comment]
Xeus also has its own C++ kernel message processing library

**Comment by jasongrout** [comment]
>  I totally agree that this should be relaxed until kernel developers have a chance to a) catch wind of this and b) apply the update.

In fact, the R discussion led to the jupyter docs being updated to make that status field explicitly mentioned in the kernel_info_reply docs: https://github.com/jupyter/jupyter_client/pull/454

**Comment by kevin-bates** [comment]
Yes, #454 was what led me to go checkout the IRkernel code to see if there was an update.

These "post-processing areas" are follow-ons to what the server is doing, so I think we're fine from a server standpoint.  The kernel provider functions are just being a little more strict than today's server code, so we should relax there as well.  Kinda wondering if a warning message should be logged (by the kernel provider layer), just to bring attention that a possible kernel update is warranted.

**Comment by jasongrout** [comment]
I think what we should have is:

* A test suite that comprehensively checks a kernel's message compliance
* An automated page that lists common kernels and their message compliance

Then kernel authors can run the compliance test suite against their kernel to see what needs to be done.
