### ISSUE TITLE
When is `execute_reply` actually sent?

### ISSUE THREAD

**Issue by mosiman** [jupyter/jupyter_client#504]
The current docs say 

> The client sends an \<action\>_request message (such as execute_request) on its shell (DEALER) socket. The kernel receives that request and immediately publishes a status: busy message on IOPub. The kernel then processes the request and sends the appropriate \<action\>_reply message, such as execute_reply

But for example if I define a client and do the following action:

```
kerClient = ... 
kerClient.execute("print('hello world')")
```

If I call all there is on the `iopub` channel (via `kerClient.get_iopub_msg()`), none of the resulting message types are `execute_reply`. (`['status', 'execute_input', 'stream', 'status']`). I assume the whole request is over when `status` is idle.

The reason I'm wondering is because I'm trying to interface with the `nbformat` library, which allows creation of output objects from iopub messages. However, since the `stream` message doesn't contain the execution count, the resulting output object from `nbformat` also doesn't contain an execution count. 

I can get the execution count from `execute_input` just fine, but it's just a bit more work if the execution count isn't contained in every message. Now I'm just curious as to when `execute_reply` is sent back, and what makes it different from the other iopub messages that are returned after an `execute_request` is sent.

**Comment by MSeal** [comment]
Sorry for the delay in responding, I missed this issue initially.

> If I call all there is on the iopub channel (via kerClient.get_iopub_msg()), none of the resulting message types are execute_reply.

That is because the execute_reply is sent on the `shell_channel`. This is a bit confusing at first, but it's part of the execution model for which clients receive which messages when there are multiple clients requesting work from the same kernel.

> I assume the whole request is over when status is idle.

Yes.

> Now I'm just curious as to when execute_reply is sent back, and what makes it different from the other iopub messages that are returned after an execute_request is sent.

Maybe take a look at [nbclient](https://github.com/jupyter/nbclient) which is the notebook execution wrapper library being pulled out of nbconvert. It has all the logic for running a notebook end-to-end with message processing and all the inherent rules of kernel execution patterns for a notebook context captured in it's Executor class. That might help, or even implement what you need already. It's going to have it's first release in a week or two, but the same code lives in nbconvert today that you can use in the meantime if you want to just import classes from PyPI packages.

**Comment by mosiman** [comment]
I see, thanks for the clarification! I'll for sure have a look at nbclient, thanks for pointing me there
