### ISSUE TITLE
Insecure Execution Mode?

### ISSUE THREAD

**Issue by MSeal** [jupyter/jupyter_client#507]
@kevin-bates I wanted to chat about maybe providing an insecure launch mode. This shouldn't be a default behavior but the number of users working on top of filesystems that can't set permission bits seems high, and usually their not in a technical position to fix the underlying issue -- or their administration prevents it. I was thinking maybe we should introduce an option to run jupyter_client which bypasses secure write with a warning message about the opt into an insecure mode.

Thoughts?

**Comment by kevin-bates** [comment]
Thanks for the ping @MSeal.

To be honest, I've always felt the filesystem was the domain/responsibility of the admin/user to protect.  That said, its prudent to create files with appropriate permissions.

If this was an option (to bypass enforcement), the concern I have is how that would be conveyed via applications, particularly when adopting the kernel-provider proposal of jupyter_kernel_mgmt, where its the 3rd-party provider that creates a connection file (if at all).

I think I'd be more inclined to replace the exception with a warning message that indicates a possible issue along with a reference for how to address it (via JUPYTER_RUNTIME_DIR for example).  Those in sensitive envs should monitor their logs and heed the warning.  

What was the reason for introducing `secure_write()` in the first place?  Yes, we need to protect the connection info, but was there some security-related issue that mandated the change?  If not, perhaps a warning message would be sufficient. However, if the change was a mandate kind of thing, then figuring out a means to explicitly bypass enforcement is probably justified.

**Comment by MSeal** [comment]
There was a security ask, yes -- I added you to the advisory thread from this repo. I think the concern with letting non-secure modes occur by default is that it can create security holes that aren't immediately obvious, without a human even taking any actions. It's real pain to scrape all process logs for warnings that your organization wants to treat as an error. Given the sheer number of issue raised by users in docker-on-windows and mounted filesystems where the filesystem admins seem to not offer the support needed to run jupyter we're forcing people to just pin back.

I'd prefer secure-by-default over secure-if-possible so a user has to set a config or launch with an env variable active to make something runnable in a situation where a) security isn't a concern and b) the user has limited control over their execution environment. But defaulting to opting out of securing secrets means any system could become insecure at any moment that a change in environment occurs without the user taking actions.

**Comment by kevin-bates** [comment]
I'm sorry, the advisory sounds familiar and I should have poked around more in that respect.  Given this was prompted by folks requiring more secure behaviors, I agree that a secure-by-default approach is required.

Regarding how to convey the intention that an insecure write will be tolerated, I would prefer env over config, primarily because `secure_write()` may not be used from a JupyterApp or Application class (and that would be required in a config approach - is that true?).  I also find envs more straightforward and a good fit in container envs.

From a naming perspective, I was thinking along a positive line like, JUPYTER_ENFORCE_SECURE_WRITES (default = True) rather than something like JUPYTER_TOLERATE_INSECURE_WRITES (default = False) but don't have a strong preference.

**Comment by kevin-bates** [comment]
@MSeal - Here's a current instance of a user that is cool with tolerating insecure mode: https://github.com/jupyter/notebook/issues/5058#issuecomment-583608922.  

We should reach a conclusion about how to go about providing this.  I'd prefer env over config since its more universal, but will go with the consensus.

**Comment by MSeal** [comment]
Ok, I'm good with an env setting. There's already precedent for this with other settings, like path settings. I'm not sure I can get to making the change this weekend but I can help review or push it next week.
