### ISSUE TITLE
Don't use deprecated cleanup() from v6.1.5

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_client#558]
Shouldn't we call `cleanup_resources()` if the version is `>=6.1.5` [here](https://github.com/jupyter/jupyter_client/blob/288b9d0927bcbf7d3e954c37d14e552f3f373324/jupyter_client/manager.py#L394-L395), instead of `>=6.2`? It prints a deprecation warning and makes a test fail [in nbclient](https://github.com/jupyter/nbclient/pull/90/checks?check_run_id=854482752).

**Comment by kevin-bates** [comment]
Unfortunately, this is considered an API change since there are existing subclasses of `KernelManager` and they will break until they are updated.  The mechanism in place gives those subclasses a chance to migrate to the new method and appropriately increase their min dependency on jupyter_client.

It's unfortunate that the deprecation warning breaks the test.  If we need to remove it, I don't really have an issue.  I suppose we could change it to `deprecationWarning` but that's essentially equivalent to its removal (although it would be there for documentation purposes I suppose).

**Comment by MSeal** [comment]
I can probably fix the nbclient test to not warn, however we are getting this warning printing out in every papermill CLI execution as well. And there's been a few questions raised by users that didn't know what it is or how to fix it.

Given this annoyance, how long should we give people to update their API calls, and how can we get the default behavior to be flipped to the non-deprecated path for these upstream libraries? Perhaps we could check dynamically if the kernel is a subclass or not for making the deprecated call until a 6.2.0 release?

**Comment by kevin-bates** [comment]
I'm sorry to hear about the grief the warning messages are causing and agree that this is a very narrow use case in which the deprecated path needs to be followed.

I think checking dynamically is a good way to go and have tested [this commit](https://github.com/jupyter/jupyter_client/commit/15253f593da06f6a3ef98101600b3f77c8176094) against Enterprise Gateway - both in the scenario where only `cleanup()` exists in the subclass, as well as when both `cleanup()` and `cleanup_resources()` exist in the subclass.

I'll be happy to submit a PR is others agree with this approach.

**Comment by MSeal** [comment]
That looks like a good solution to me! Happy to merge that and release it.
