### ISSUE TITLE
NotImplementedError on Windows with python 3.8

### ISSUE THREAD

**Issue by s-weigand** [jupyter/jupyter_client#583]
I [came across](https://github.com/s-weigand/nbsphinx/runs/1175280391?check_suite_focus=true) a `NotImplementedError ` on Windows when using python 3.8.
After some digging I found that this is a [known issue with tornado](https://github.com/tornadoweb/tornado/issues/2608) and [originates from `pyzmq`](https://github.com/zeromq/pyzmq/issues/1423) + how python 3.8 handles proactor event loop.

Luckily there already is a [suggested solution for this problem](https://github.com/tornadoweb/tornado/issues/2608#issuecomment-619524992) 😄

**Comment by kevin-bates** [comment]
What application are you experiencing this with?  The convention Jupyter has used for this issue is that the event loop policy be set in the application.  That's been true for [Notebook](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1993), [Jupyter Server](https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/serverapp.py#L1607) and [IPyKernel](https://github.com/ipython/ipykernel/blob/master/ipykernel/kernelapp.py#L508) to which I'm aware.

**Comment by MSeal** [comment]
Unfortunately it's a low level Python + Windows issue that we can't directly solve. All other clients have had to introduce the same work-around if they are main entrypoints for execution (e.g. papermill & nbconvert beyond that list Kevin gave).

**Comment by s-weigand** [comment]
@kevin-bates Thanks for the info about the convention.
> The convention Jupyter has used for this issue is that the event loop policy be set in the application.

I was using [nbsphinx](https://github.com/spatialaudio/nbsphinx), which is a sphinx extension to create documentation from notebooks.
Since the exception was raised when executing a notebook with `jupyter_client` (called via [`nbclient`](https://github.com/jupyter/nbclient)), I opened the issue here.
But now knowing the convention, I will make a PR at `nbsphinx`.

**Comment by kevin-bates** [comment]
Perfect - thank you Sebastian.  I'm going ahead with this closure. We can re-open should we find a need to do so later.

**Comment by mgeier** [comment]
For reference, the underlying Python issue is https://bugs.python.org/issue37373.

**Comment by kevin-bates** [comment]
Thanks Matthias - that is helpful and interesting to see it playing out.
