### ISSUE TITLE
kernel can only autorestart once

### ISSUE THREAD

**Issue by mofanke** [jupyter/jupyter_client#689]
kernel can only autorestart once
Name: jupyter-client
Version: 7.0.2

kill kernel process first time, it will autorestart . kill it agian , nothing will happen

**Comment by mofanke** [comment]
seems self.shutting_down in KernelManager never set to False ,after restart

**Comment by kevin-bates** [comment]
Hmm - I'm not experiencing this.  If I kill the kernel pid, the auto-restart takes place each time (across all 3 attempts).  That said, I see what you mean regarding `self.shutting_down` and it seems it deserves a reset in the post start method.  Did you want to take a crack at this?  Since I'm not reproducing this, it would be good for you to at least check out the solution (from wherever that comes).

**Comment by mofanke** [comment]
this issue occurred  when  jupyter-client==7.0.2,  and i add  "self.shutting_down = False"  in  funciton "async def _async_post_start_kernel(self, **kw) -> None:"    it will be ok

**Comment by kevin-bates** [comment]
Hi @mofanke - thanks for the update. 

Yes, that sounds like the correct approach.  Did you want to go about creating a pull request for this?

**Comment by mofanke** [comment]
fixed
