### ISSUE TITLE
`_stdin_hook_default` incorrectly uses `msg_ready`

### ISSUE THREAD

**Issue by BrenBarn** [jupyter/jupyter_client#813]
See [this line](https://github.com/jupyter/jupyter_client/blob/c81771416d9e09e0e92be799f3e8549d0db57e43/jupyter_client/client.py#L254).  `msg_ready` is now async, so its return value can't be treated as a boolean anymore.  I suppose it needs to be wrapped in `run_sync`.

**Comment by davidbrochart** [comment]
Thanks for reporting @BrenBarn.
Indeed, this cannot work. Rather than wrapping in `run_sync`, we could make `_stdin_hook_default` an async function, and support both async and sync [stdin_hook](https://github.com/jupyter/jupyter_client/blob/c81771416d9e09e0e92be799f3e8549d0db57e43/jupyter_client/client.py#L424). What do you think?

**Comment by BrenBarn** [comment]
Having support for either sync or async `stdin_hook` would be great.  I don't have much of an opinion on whether `_stdin_hook_default` should be sync or async, although I suppose making it async makes sense as it is called by an async function and calls async functions itself.
